### ISSUE TITLE
新手求助，在执行翻译时报错

### ISSUE THREAD

**Issue by imanuelwang** [Byaidu/PDFMathTranslate#132]
## 问题描述
D:\Trade\书籍>pdf2zh "GS-understand technical analysis.pdf" -s openai:gpt-4o
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\muxi\AppData\Local\Programs\Python\Python311\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
  File "C:\Users\muxi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdf2zh\pdf2zh.py", line 279, in main
    extract_text(**vars(parsed_args))
  File "C:\Users\muxi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdf2zh\pdf2zh.py", line 90, in extract_text
    model = DocLayoutModel.load_available()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\muxi\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdf2zh\doclayout.py", line 33, in load_available
    raise ImportError(
ImportError: Please install the `torch` or `onnx` feature to use the DocLayout model.

D:\Trade\书籍>

**Comment by milk2715093695** [comment]
试试在虚拟环境里面安装？我室友之前也是这个问题，我让他卸了全局的torch和pdf2zh然后进了虚拟环境再安装pdf2zh就没问题了。

**Comment by imanuelwang** [comment]
> 试试在虚拟环境里面安装？我室友之前也是这个问题，我让他卸了全局的torch和pdf2zh然后进了虚拟环境再安装pdf2zh就没问题了。

谢谢

**Comment by imanuelwang** [comment]
> 建议重装一遍
重装后还是一样的问题
