### ISSUE TITLE
IndexError: string index out of range during PDF translation

### ISSUE THREAD

**Issue by milk2715093695** [Byaidu/PDFMathTranslate#150]
## 问题描述
在使用 pdf2zh 命令翻译 PDF 文件时，程序正常生成了中间文件 2024 APMCM Problem A-en.pdf，但翻译过程中出现索引越界错误 `IndexError: string index out of range`，最终程序终止，翻译失败。

## 重现步骤
1. 下载并且使用下方提供的测试 PDF 文档（文件名为 2024 APMCM Problem A.pdf ）
2. 在终端运行以下命令：
```bash 
pdf2zh 2024\ APMCM\ Problem\ A.pdf
```
3. 程序生成中间文件 2024 APMCM Problem A-en.pdf。
4. 翻译进行到 67% 时，报错并终止。

## 错误信息和日志

错误日志如下所示：

```text
(base) mac@macs-MacBook-Air 2024 APMCM Problem A % pdf2zh 2024\ APMCM\ Problem\ A.pdf
 67%|███████████████████████████████████▎                 | 4/6 [00:02<00:01,  1.38it/s]
Traceback (most recent call last):
  File "/Users/mac/micromamba/bin/pdf2zh", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 279, in main
    extract_text(**vars(parsed_args))
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 121, in extract_text
    obj_patch: dict = pdf2zh.high_level.extract_text_to_fp(fp, **locals())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/high_level.py", line 212, in extract_text_to_fp
    interpreter.process_page(page)
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/pdfinterp.py", line 1021, in process_page
    ops_new = self.device.end_page(page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/converter.py", line 112, in end_page
    return self.receive_layout(self.cur_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/converter.py", line 638, in receive_layout
    if len(var[vid]) == 1 and unicodedata.category(var[vid][0].get_text()[0]) in ["Lm", "Mn", "Sk"]:  # 文字修饰符
                                                   ~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: string index out of range
```

如下图所示：
<img width="1440" alt="截屏2024-11-28 22 10 38" src="https://github.com/user-attachments/assets/b83b1119-32ac-4815-9261-c0bf8f9e69d6">

## 环境信息
1. 应该可以确认不是网络问题，翻译其他 PDF 时完全正确。
2. 操作系统：ProductName: macOS
ProductVersion: 14.6.1
BuildVersion: 23G93
3. python 版本：3.12
4. 安装方式：micromamba

## 测试文档
问题可能与特定 PDF 文件相关，已附上出现问题的 PDF 文件供测试：

[2024 APMCM Problem A.pdf](https://github.com/user-attachments/files/17949145/2024.APMCM.Problem.A.pdf)

**Comment by reycn** [comment]
最新版本未能复现此问题，暂时关闭 Issue；如有进一步的线索再次打开追踪。

## 复现截图
<img width="1364" alt="image" src="https://github.com/user-attachments/assets/75bdd03d-4ca1-4d6f-8eae-5f598d625054">

**Comment by Byaidu** [comment]
哦这个是刚修复，但是还没推送

**Comment by reycn** [comment]
> 哦这个是刚修复，但是还没推送

太快了！！
