### ISSUE TITLE
deeplx auth key怎么填,总是报错

### ISSUE THREAD

**Issue by dowier** [Byaidu/PDFMathTranslate#156]
## deeplx auth key怎么填

E:\AI\github\PDFMathTranslate (main -> origin)
(myenv) λset DEEPLX_SERVER_URL=http://localhost:6119/translate

E:\AI\github\PDFMathTranslate (main -> origin)
(myenv) λpdf2zh "3.pdf" -f "(CM[^RT].*|MS.*|.*Ital)" -c "(\(|\||\)|\+|=|\d|[\u0080-\ufaff])" -s deepl
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "E:\AI\github\PDFMathTranslate\myenv\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
  File "E:\AI\github\PDFMathTranslate\myenv\Lib\site-packages\pdf2zh\pdf2zh.py", line 259, in main
    extract_text(**vars(parsed_args))
  File "E:\AI\github\PDFMathTranslate\myenv\Lib\site-packages\pdf2zh\pdf2zh.py", line 102, in extract_text
    obj_patch: dict = pdf2zh.high_level.extract_text_to_fp(fp, **locals())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\github\PDFMathTranslate\myenv\Lib\site-packages\pdf2zh\high_level.py", line 51, in extract_text_to_fp
    device = TranslateConverter(
             ^^^^^^^^^^^^^^^^^^^
  File "E:\AI\github\PDFMathTranslate\myenv\Lib\site-packages\pdf2zh\converter.py", line 136, in __init__
    self.translator: BaseTranslator = DeepLTranslator(service, lang_out, lang_in, None)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\github\PDFMathTranslate\myenv\Lib\site-packages\pdf2zh\translator.py", line 249, in __init__
    self.client = deepl.Translator(auth_key, server_url=server_url)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\github\PDFMathTranslate\myenv\Lib\site-packages\deepl\translator.py", line 93, in __init__
    raise ValueError("auth_key must not be empty")
ValueError: auth_key must not be empty

**Comment by dowier** [comment]
E:\AI\github\PDFMathTranslate (main -> origin)
λmyenv\Scripts\activate

E:\AI\github\PDFMathTranslate (main -> origin)
(myenv) λset DEEPLX_SERVER_URL=http://localhost:6119/translate

E:\AI\github\PDFMathTranslate (main -> origin)
(myenv) λpdf2zh "2015Cerium Anomaly at Microscale in Fossils.pdf" -f "(CM[^RT].*|MS.*|.*Ital)" -c "(\(|\||\)|\+|= |\d|[\u0080-\ufaff])" -s deeplx
  0%|                                                                                     | 0/10 [00:00<?, ?it/s]ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404
ERROR:pdf2zh.converter:HTTP error: 404

**Comment by dowier** [comment]
更新后, 能运行了,但是报错404

**Comment by dowier** [comment]
没有解决，不知道啊



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月02日 17:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>、State ***@***.***> |
| 主题 | Re: [Byaidu/PDFMathTranslate] deeplx auth key怎么填,总是报错 (Issue #156) |

这个404咋解决的呀
