### ISSUE TITLE
将中文文档翻译为英文时遇到的两类错误：字体处理异常与 PDF 对象解析问题

### ISSUE THREAD

**Issue by milk2715093695** [Byaidu/PDFMathTranslate#158]
## 问题描述
在使用 pdf2zh 翻译将中文 PDF 文档翻译为英文时，遇到两类不同的问题，导致翻译失败。以下是详细描述：

### 第一类错误：字体解析问题
A.pdf 是通过使用 pdf2zh 将英文文档翻译为中文文档得到的结果。

**复现步骤**
1. 下载下方提供的 A.pdf 文档
2. 使用以下命令将 A.pdf 翻译回中文文档
```bash
pdf2zh A.pdf -li zh-CN -lo en
```
3. 中间文件 A-en.pdf正常生成
4. 字体解析出现问题

**报错日志**
```text
(base) mac@macs-MacBook-Air test % pdf2zh A.pdf -li zh-CN -lo en
  0%|                                | 0/6 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/Users/mac/micromamba/bin/pdf2zh", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 259, in main
    extract_text(**vars(parsed_args))
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 102, in extract_text
    obj_patch: dict = pdf2zh.high_level.extract_text_to_fp(fp, **locals())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/high_level.py", line 112, in extract_text_to_fp
    interpreter.process_page(page)
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/pdfinterp.py", line 266, in process_page
    ops_new = self.device.end_page(page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/converter.py", line 50, in end_page
    return self.receive_layout(self.cur_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/converter.py", line 216, in receive_layout
    or vflag(child.fontname, child.get_text())                                              # 3. 公式字体
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/converter.py", line 172, in vflag
    font = font.split("+")[-1]      # 字体名截断
           ^^^^^^^^^^^^^^^
TypeError: a bytes-like object is required, not 'str'
```

**图片展示：**
<img width="1440" alt="截屏2024-12-01 20 51 51" src="https://github.com/user-attachments/assets/94235f7b-80c6-4872-9bde-861ce4edcf83">

### 第二类错误：PDF 对象解析问题
B.pdf 是使用 overleaf 平台，由 LaTeX 编写的原生中文文档

**复现步骤**
1. 下载下方提供的 B.pdf 文档
2. 使用以下命令将 B.pdf 翻译为中文文档
```bash
pdf2zh B.pdf -li zh-CN -lo en
```
3. 中间文件 B-en.pdf正常生成
4. PDF 对象解析出现问题

**报错日志**
```text
(base) mac@macs-MacBook-Air test % pdf2zh B.pdf -li zh-CN -lo en
  0%|                                | 0/7 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/Users/mac/micromamba/bin/pdf2zh", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 259, in main
    extract_text(**vars(parsed_args))
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 102, in extract_text
    obj_patch: dict = pdf2zh.high_level.extract_text_to_fp(fp, **locals())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdf2zh/high_level.py", line 69, in extract_text_to_fp
    for pageno, page in progress:
                        ^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdfminer/pdfpage.py", line 127, in create_pages
    yield cls(document, objid, tree, next(page_labels))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/micromamba/lib/python3.12/site-packages/pdfminer/pdfpage.py", line 63, in __init__
    mediabox_params: List[Any] = [
                                 ^
TypeError: 'PDFObjRef' object is not iterable
```

**图片展示**
<img width="1440" alt="截屏2024-12-01 20 52 13" src="https://github.com/user-attachments/assets/e937f94c-e753-443e-870d-6a829698cc5b">

## 排除网络问题与中文文档的问题
**排除网络问题**
<img width="1440" alt="截屏2024-12-01 21 40 10" src="https://github.com/user-attachments/assets/06fa11d2-c9b9-4181-871a-29dd0ca7f9c8">

**排除中文的问题**
C.pdf 是我在本地使用 Visual Studio Code + TexShop + XeLaTeX 编写的中文 PDF，翻译完全正常（虽然生成的文档命名不太对，被命名成了 C-zh.pdf，但是无伤大雅，实际上确实是翻译成了英文），小部分字体重叠问题是因为英文比中文长导致放不下。

<img width="496" alt="截屏2024-12-01 22 11 24" src="https://github.com/user-attachments/assets/4036553e-363a-4028-a425-c4da7738c73a">

## 环境信息
1. 应该可以确认不是网络问题，翻译其他 PDF 时完全正确，可能与字体有关，overleaf 使用的与我本地的字体不同。
2. 操作系统：ProductName: macOS
ProductVersion: 14.6.1
BuildVersion: 23G93
3. python 版本：3.12
4. 安装方式：micromamba

## 测试文档
[A.pdf](https://github.com/user-attachments/files/17969009/A.pdf)
[B.pdf](https://github.com/user-attachments/files/17969010/B.pdf)
C.pdf 是能够正常翻译的中文文档，且其中出现了我的姓名，恕无法提供，十分抱歉。

**Comment by Byaidu** [comment]
感谢反馈，A已修复

B是pdfminer的问题，超出项目范围了
