### ISSUE TITLE
pdf2zh/doclayout.py  TorchModel init 缺乏doclayout_yolo报错但是提示 缺乏torch

### ISSUE THREAD

**Issue by benjohn18** [Byaidu/PDFMathTranslate#163]
## 问题描述
PDFMathTranslate/tree/main/pdf2zh/doclayout.py

class TorchModel(DocLayoutModel):
    def __init__(self, model_path: str):
        try:
            import doclayout_yolo
        except ImportError:
            raise ImportError(
                "Please install the `torch` feature to use the Torch model."
            )

## 测试文档
Traceback (most recent call last):
  File "D:\anaconda\envs\py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\anaconda\envs\py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\anaconda\envs\py310\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\anaconda\envs\py310\lib\site-packages\pdf2zh\pdf2zh.py", line 262, in main
    extract_text(**vars(parsed_args))
  File "D:\anaconda\envs\py310\lib\site-packages\pdf2zh\pdf2zh.py", line 56, in extract_text
    model = DocLayoutModel.load_available()
  File "D:\anaconda\envs\py310\lib\site-packages\pdf2zh\doclayout.py", line 33, in load_available
    raise ImportError(
ImportError: Please install the `torch` or `onnx` feature to use the DocLayout model.

## 解决方法
这里如果是缺乏doclayout_yolo库却提示缺乏torch，我经过多次重复安装torch，都不能解决问题，最后发现是这里的引导出错，try 把报错覆盖了，只提示缺乏torch。
解决方法，安装库  pip install doclayout_yolo
建议修改这里的提示

**Comment by Byaidu** [comment]
感谢反馈，下个版本可能直接把torch移除了
