### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by h9052300** [Byaidu/PDFMathTranslate#17]
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\x1090102\AppData\Local\Programs\Python\Python312\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
  File "C:\Users\x1090102\AppData\Local\Programs\Python\Python312\Lib\site-packages\pdf2zh\pdf2zh.py", line 229, in main
    extract_text(**vars(parsed_args))
  File "C:\Users\x1090102\AppData\Local\Programs\Python\Python312\Lib\site-packages\pdf2zh\pdf2zh.py", line 102, in extract_text
    obj_patch:dict=pdf2zh.high_level.extract_text_to_fp(fp, **locals())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\x1090102\AppData\Local\Programs\Python\Python312\Lib\site-packages\pdf2zh\high_level.py", line 187, in extract_text_to_fp
    interpreter.process_page(page)
  File "C:\Users\x1090102\AppData\Local\Programs\Python\Python312\Lib\site-packages\pdf2zh\pdfinterp.py", line 1011, in process_page
    self.obj_patch[page_objids[0]]=f'q {ops_base}Q 1 0 0 1 {x0} {y0} cm {ops_new}' # ops_base 里可能有图，需要让 ops_new 里的文字覆盖在上面，使用 q/Q 重置位置矩阵
                   ~~~~~~~~~~~^^^
IndexError: list index out of range

您好，请问我该如何处理以上错误?

**Comment by Byaidu** [comment]
麻烦发一下测试用的 pdf
