### ISSUE TITLE
docker运行报错

### ISSUE THREAD

**Issue by QianXuZOZ** [Byaidu/PDFMathTranslate#184]
## 问题描述
看起来好像和huggingface_hub有关，但是这个东西在doceker里怎么解决哇

2024-12-09 00:47:46 Traceback (most recent call last):
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 466, in _make_request
2024-12-09 00:47:46     self._validate_conn(conn)
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
2024-12-09 00:47:46     conn.connect()
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 730, in connect
2024-12-09 00:47:46     sock_and_verified = _ssl_wrap_socket_and_match_hostname(
2024-12-09 00:47:46                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/connection.py", line 909, in _ssl_wrap_socket_and_match_hostname
2024-12-09 00:47:46     ssl_sock = ssl_wrap_socket(
2024-12-09 00:47:46                ^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 469, in ssl_wrap_socket
2024-12-09 00:47:46     ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
2024-12-09 00:47:46                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/util/ssl_.py", line 513, in _ssl_wrap_socket_impl
2024-12-09 00:47:46     return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
2024-12-09 00:47:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/ssl.py", line 455, in wrap_socket
2024-12-09 00:47:46     return self.sslsocket_class._create(
2024-12-09 00:47:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/ssl.py", line 1041, in _create
2024-12-09 00:47:46     self.do_handshake()
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/ssl.py", line 1319, in do_handshake
2024-12-09 00:47:46     self._sslobj.do_handshake()
2024-12-09 00:47:46 TimeoutError: _ssl.c:983: The handshake operation timed out
2024-12-09 00:47:46 
2024-12-09 00:47:46 The above exception was the direct cause of the following exception:
2024-12-09 00:47:46 
2024-12-09 00:47:46 Traceback (most recent call last):
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
2024-12-09 00:47:46     resp = conn.urlopen(
2024-12-09 00:47:46            ^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 843, in urlopen
2024-12-09 00:47:46     retries = retries.increment(
2024-12-09 00:47:46               ^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
2024-12-09 00:47:46     raise reraise(type(error), error, _stacktrace)
2024-12-09 00:47:46           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
2024-12-09 00:47:46     raise value
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
2024-12-09 00:47:46     response = self._make_request(
2024-12-09 00:47:46                ^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 490, in _make_request
2024-12-09 00:47:46     raise new_e
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 468, in _make_request
2024-12-09 00:47:46     self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
2024-12-09 00:47:46     raise ReadTimeoutError(
2024-12-09 00:47:46 urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=1)
2024-12-09 00:47:46 
2024-12-09 00:47:46 During handling of the above exception, another exception occurred:
2024-12-09 00:47:46 
2024-12-09 00:47:46 Traceback (most recent call last):
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1376, in _get_metadata_or_catch_error
2024-12-09 00:47:46     metadata = get_hf_file_metadata(
2024-12-09 00:47:46                ^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
2024-12-09 00:47:46     return fn(*args, **kwargs)
2024-12-09 00:47:46            ^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1296, in get_hf_file_metadata
2024-12-09 00:47:46     r = _request_wrapper(
2024-12-09 00:47:46         ^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 277, in _request_wrapper
2024-12-09 00:47:46     response = _request_wrapper(
2024-12-09 00:47:46                ^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 300, in _request_wrapper
2024-12-09 00:47:46     response = get_session().request(method=method, url=url, **params)
2024-12-09 00:47:46                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
2024-12-09 00:47:46     resp = self.send(prep, **send_kwargs)
2024-12-09 00:47:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
2024-12-09 00:47:46     r = adapter.send(request, **kwargs)
2024-12-09 00:47:46         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/utils/_http.py", line 93, in send
2024-12-09 00:47:46     return super().send(request, *args, **kwargs)
2024-12-09 00:47:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
2024-12-09 00:47:46     raise ReadTimeout(e, request=request)
2024-12-09 00:47:46 requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='huggingface.co', port=443): Read timed out. (read timeout=1)"), '(Request ID: ad096c2b-8d18-424a-87b2-898e46353c0c)')
2024-12-09 00:47:46 
2024-12-09 00:47:46 The above exception was the direct cause of the following exception:
2024-12-09 00:47:46 
2024-12-09 00:47:46 Traceback (most recent call last):
2024-12-09 00:47:46   File "/usr/local/bin/pdf2zh", line 5, in <module>
2024-12-09 00:47:46     from pdf2zh.pdf2zh import main
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 27, in <module>
2024-12-09 00:47:46     model = DocLayoutModel.load_available()
2024-12-09 00:47:46             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/pdf2zh/doclayout.py", line 21, in load_available
2024-12-09 00:47:46     return DocLayoutModel.load_onnx()
2024-12-09 00:47:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/pdf2zh/doclayout.py", line 13, in load_onnx
2024-12-09 00:47:46     model = OnnxModel.from_pretrained(
2024-12-09 00:47:46             ^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/pdf2zh/doclayout.py", line 73, in from_pretrained
2024-12-09 00:47:46     pth = hf_hub_download(repo_id=repo_id, filename=filename, etag_timeout=1)
2024-12-09 00:47:46           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
2024-12-09 00:47:46     return fn(*args, **kwargs)
2024-12-09 00:47:46            ^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 862, in hf_hub_download
2024-12-09 00:47:46     return _hf_hub_download_to_cache_dir(
2024-12-09 00:47:46            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 969, in _hf_hub_download_to_cache_dir
2024-12-09 00:47:46     _raise_on_head_call_error(head_call_error, force_download, local_files_only)
2024-12-09 00:47:46   File "/usr/local/lib/python3.12/site-packages/huggingface_hub/file_download.py", line 1487, in _raise_on_head_call_error
2024-12-09 00:47:46     raise LocalEntryNotFoundError(
2024-12-09 00:47:46 huggingface_hub.errors.LocalEntryNotFoundError: An error happened while trying to locate the file on the Hub and we cannot find the requested files in the local cache. Please check your connection and try again or make sure your Internet connection is on.

**Comment by Byaidu** [comment]
加参数-e HF_ENDPOINT=https://hf-mirror.com
