### ISSUE TITLE
报错：AttributeError

### ISSUE THREAD

**Issue by ZzzzRyan** [Byaidu/PDFMathTranslate#23]
运行后报错：

```powershell
~> pdf2zh IEEE_SPL2016_CramrRao_Bounds_for_Underdetermined_Source_Localization.pdf
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\05_MyData\Projects\PythonProjects\Pdf2zh\pdf2zh\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
    sys.exit(main())
             ~~~~^^
  File "D:\05_MyData\Projects\PythonProjects\Pdf2zh\pdf2zh\Lib\site-packages\pdf2zh\pdf2zh.py", line 214, in main
    extract_text(**vars(parsed_args))
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "D:\05_MyData\Projects\PythonProjects\Pdf2zh\pdf2zh\Lib\site-packages\pdf2zh\pdf2zh.py", line 71, in extract_text
    model = lp.EfficientDetLayoutModel("lp://efficientdet/MFD/tf_efficientdet_d0",pth)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'layoutparser' has no attribute 'EfficientDetLayoutModel'
```

截图：

![image](https://github.com/user-attachments/assets/3f16ee49-c77f-4c40-9dfd-4b803a9e5ce8)

当前是通过 pip 安装在一个虚拟环境中运行的，首次启动自动下载了一个什么组件，之后就开始报错。

**Comment by Byaidu** [comment]
奇怪了，为什么你会下载到旧版的程序呢，执行 pip install -U pdf2zh 更新版本试试

**Comment by Byaidu** [comment]
```
Collecting pdf2zh
  Using cached pdf2zh-1.6.4-py3-none-any.whl.metadata (3.1 kB)
  Using cached pdf2zh-1.6.3-py3-none-any.whl.metadata (3.1 kB)
  Using cached pdf2zh-1.6.2-py3-none-any.whl.metadata (3.0 kB)
  Using cached pdf2zh-1.6.1-py3-none-any.whl.metadata (3.0 kB)
  Using cached pdf2zh-1.6.0-py3-none-any.whl.metadata (3.0 kB)
  Using cached pdf2zh-1.5.9-py3-none-any.whl.metadata (2.9 kB)
  Using cached pdf2zh-1.5.8-py3-none-any.whl.metadata (2.9 kB)
INFO: pip is still looking at multiple versions of doclayout-yolo to determine which version is compatible with other requirements. This could take a while.
  Using cached pdf2zh-1.5.7-py3-none-any.whl.metadata (2.9 kB)
  Using cached pdf2zh-1.5.6-py3-none-any.whl.metadata (2.9 kB)
  Using cached pdf2zh-1.5.5-py3-none-any.whl.metadata (2.9 kB)
  Using cached pdf2zh-1.5.4-py3-none-any.whl.metadata (2.9 kB)
  Using cached pdf2zh-1.5.3-py3-none-any.whl.metadata (2.9 kB)
```
直接被 pip 从 1.6.5 降级到 1.5.3 了……

感觉有可能是源的问题，试试 pip install pdf2zh -i https://pypi.org/simple

**Comment by ZzzzRyan** [comment]
之前也没有改过源，默认的 https://pypi.org/simple. 我试了 `pip install pdf2zh -i https://pypi.org/simple` 之后还是一样，输出没有变化。

然后我怀疑是版本问题，刚刚是 `python 3.13.0`，我换到了 `python 3.10.11` 重新创建虚拟环境安装一遍，结果就没问题了😂.

这次下载版本确实是 1.6.5
```python
Collecting pdf2zh
  Downloading pdf2zh-1.6.5-py3-none-any.whl (151 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.5/151.5 kB 821.0 kB/s eta 0:00:00
```

---

但是有个问题，为啥直接连带了个 `ollama` ？我下完后文件夹直接到了 1.5G，汗

**Comment by ZzzzRyan** [comment]
👌了解，感谢解答🙏

工具很赞！公式基本都很完整保留下来了。
