### ISSUE TITLE
bug (pdf reader): unknown base font

### ISSUE THREAD

**Issue by reycn** [Byaidu/PDFMathTranslate#295]
## Bug

If the font name of a PDF file is unknown, the program will raise a `KeyError: <PDFType1Font: basefont='unknown'>`, as follows:

```
Traceback (most recent call last):
  File "/Users/rey/miniconda3/envs/pdf/bin/pdf2zh", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/rey/Developer/PDFMathTranslate.Origin/pdf2zh/pdf2zh.py", line 192, in main
    translate(**vars(parsed_args))
  File "/Users/rey/Developer/PDFMathTranslate.Origin/pdf2zh/high_level.py", line 359, in translate
    s_mono, s_dual = translate_stream(
                     ^^^^^^^^^^^^^^^^^
  File "/Users/rey/Developer/PDFMathTranslate.Origin/pdf2zh/high_level.py", line 234, in translate_stream
    obj_patch: dict = translate_patch(fp, prompt=kwarg["prompt"], **locals())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rey/Developer/PDFMathTranslate.Origin/pdf2zh/high_level.py", line 165, in translate_patch
    interpreter.process_page(page)
  File "/Users/rey/Developer/PDFMathTranslate.Origin/pdf2zh/pdfinterp.py", line 270, in process_page
    ops_new = self.device.end_page(page)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rey/Developer/PDFMathTranslate.Origin/pdf2zh/converter.py", line 61, in end_page
    return self.receive_layout(self.cur_item)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rey/Developer/PDFMathTranslate.Origin/pdf2zh/converter.py", line 429, in receive_layout
    ops += f"/{self.fontid[vch.font]} {vch.size:f} Tf 1 0 0 1 {x + vch.x0 - var[vid][0].x0:f} {fix + y + vch.y0 - var[vid][0].y0:f} Tm [<{raw_string(self.fontid[vch.font], vc)}>] TJ "
               ~~~~~~~~~~~^^^^^^^^^^
KeyError: <PDFType1Font: basefont='unknown'>
```

The program itself runs well, passing all tests and translating other documents.

## Sample Document

> [translate.cli.font.unknown.pdf](https://github.com/user-attachments/files/18193545/translate.cli.font.unknown.pdf)

**Comment by reycn** [comment]
A corresponding test case has written in [CI](https://github.com/Byaidu/PDFMathTranslate/blob/979150ca2dfa48eb21a8d6fbbd9b817443a34823/.github/workflows/python-build.yml#L42), yet not active before fixing the bug.
