### ISSUE TITLE
pymupdf.mupdf.FzErrorSyntax: code=8: invalid key in dict

### ISSUE THREAD

**Issue by yshi100** [Byaidu/PDFMathTranslate#301]
## 问题描述
Traceback (most recent call last):
  File "/home/yshi/.pyenv/versions/3.12.0/bin/pdf2zh", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 164, in main
    translate(**vars(parsed_args))
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/high_level.py", line 278, in translate
    s_mono, s_dual = translate_stream(s_raw, **locals())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/high_level.py", line 212, in translate_stream
    doc_zh.save(fp)
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pymupdf/__init__.py", line 5646, in save
    mupdf.pdf_write_document(pdf, out, opts)
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pymupdf/mupdf.py", line 52177, in pdf_write_document
    return _mupdf.pdf_write_document(doc, out, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pymupdf.mupdf.FzErrorSyntax: code=8: invalid key in dict

## 测试文档

[The Async-First Playbook Remote Collaboration Techniques for Agile Software Teams (Sumeet Moghe) (Z-Library).pdf](https://github.com/user-attachments/files/18206906/The.Async-First.Playbook.Remote.Collaboration.Techniques.for.Agile.Software.Teams.Sumeet.Moghe.Z-Library.pdf)

**Comment by Byaidu** [comment]
应该是上游的问题，你可以到 pymupdf 项目下反馈
