### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by yshi100** [Byaidu/PDFMathTranslate#32]
pdf2zh m.pdf                                                                            0 <<18:39:05
Downloading...
Traceback (most recent call last):
  File "/home/yshi/.pyenv/versions/3.12.0/bin/pdf2zh", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 229, in main
    extract_text(**vars(parsed_args))
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 73, in extract_text
    urllib.request.urlretrieve("http://huggingface.co/juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt",pth)
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/urllib/request.py", line 1373, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/urllib/request.py", line 1348, in do_open
    r = h.getresponse()
        ^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/http/client.py", line 1411, in getresponse
    response.begin()
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/http/client.py", line 324, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/http/client.py", line 285, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by Byaidu** [comment]
网络问题
