### ISSUE TITLE
 ops_base 里可能有图

### ISSUE THREAD

**Issue by yshi100** [Byaidu/PDFMathTranslate#33]
ckpt = torch.load(file, map_location="cpu")
  6%|████▍                                                                           | 23/410 [00:29<08:18,  1.29s/it]
Traceback (most recent call last):
  File "/home/yshi/.pyenv/versions/3.12.0/bin/pdf2zh", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 229, in main
    extract_text(**vars(parsed_args))
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 102, in extract_text
    obj_patch:dict=pdf2zh.high_level.extract_text_to_fp(fp, **locals())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/high_level.py", line 187, in extract_text_to_fp
    interpreter.process_page(page)
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/pdfinterp.py", line 1011, in process_page
    self.obj_patch[page_objids[0]]=f'q {ops_base}Q 1 0 0 1 {x0} {y0} cm {ops_new}' # ops_base 里可能有图，需要让 ops_new 里的文字覆盖在上面，使用 q/Q 重置位置矩阵
                   ~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by Byaidu** [comment]
麻烦发下文件

**Comment by yshi100** [comment]
[Modern Front-End Development for Rails Hotwire, Stimulus, Turbo, and React, 2nd Edition (Noel Rappin) (Z-Library).pdf](https://github.com/user-attachments/files/17701941/Modern.Front-End.Development.for.Rails.Hotwire.Stimulus.Turbo.and.React.2nd.Edition.Noel.Rappin.Z-Library.pdf)
