### ISSUE TITLE
api方式调用出错，用的gemini模型

### ISSUE THREAD

**Issue by thundergw** [Byaidu/PDFMathTranslate#334]
python代码如下：
from pdf2zh import translate, translate_stream

params = {"lang_in": "en", "lang_out": "zh", "service": "gemini",  "thread": 4,'api_key':'xxx'} 
filename="q.pdf"
file_mono, file_dual = translate(files=[filename], **params)[0]
with open(filename, "rb") as f:
    stream_mono, stream_dual = translate_stream(stream=f.read(), **params)

出错提示
Traceback (most recent call last):
  File "D:\pycharm\pythonProject3\pdf2cn\main.py", line 5, in <module>
    file_mono, file_dual = translate(files=[filename], **params)[0]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm\pythonProject3\venv\Lib\site-packages\pdf2zh\high_level.py", line 278, in translate
    s_mono, s_dual = translate_stream(s_raw, **locals())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm\pythonProject3\venv\Lib\site-packages\pdf2zh\high_level.py", line 213, in translate_stream
    obj_patch: dict = translate_patch(fp, **locals())
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm\pythonProject3\venv\Lib\site-packages\pdf2zh\high_level.py", line 91, in translate_patch
    device = TranslateConverter(
             ^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm\pythonProject3\venv\Lib\site-packages\pdf2zh\converter.py", line 148, in __init__
    self.translator = translator(lang_in, lang_out, service_model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pycharm\pythonProject3\venv\Lib\site-packages\pdf2zh\translator.py", line 301, in __init__
    super().__init__(lang_in, lang_out, model, base_url=base_url, api_key=api_key)
  File "D:\pycharm\pythonProject3\venv\Lib\site-packages\pdf2zh\translator.py", line 213, in __init__
    self.client = openai.OpenAI(base_url=base_url, api_key=api_key)
                  ^^^^^^^^^^^^^
AttributeError: module 'openai' has no attribute 'OpenAI'

## 问题描述
请对问题进行描述，并提供日志或截图
请确认 issues 中没有相同问题且完整阅读 wiki
**本项目不处理网络环境引发的问题**（例如 empty translation result/connection reset/check_hostname requires server_hostname/certificate verify failed/unable to connect to proxy/LocalEntryNotFoundError）

## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档

**Comment by Byaidu** [comment]
pip install -U openai
