### ISSUE TITLE
pymupdf.mupdf.FzErrorFormat: code=7: cannot parse object (1392 0 R)

### ISSUE THREAD

**Issue by fanenr** [Byaidu/PDFMathTranslate#362]
## 问题描述
翻译到 100% 后出错：

```bash
MuPDF error: syntax error: expected object number

MuPDF error: format error: Repair failed already - not trying again

Traceback (most recent call last):
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/gradio/queueing.py", line 625, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/gradio/blocks.py", line 2047, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/gradio/blocks.py", line 1594, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2505, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/anyio/_backends/_asyncio.py", line 1005, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/gradio/utils.py", line 869, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/pdf2zh/gui.py", line 165, in translate_file
    translate(**param)
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/pdf2zh/high_level.py", line 278, in translate
    s_mono, s_dual = translate_stream(s_raw, **locals())
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/pdf2zh/high_level.py", line 226, in translate_stream
    return doc_zh.write(deflate=1), doc_en.write(deflate=1)
                                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/pymupdf/__init__.py", line 5952, in write
    self.save(
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/pymupdf/__init__.py", line 5652, in save
    mupdf.pdf_write_document(pdf, out, opts)
  File "/home/arthur/.local/share/pipx/venvs/pdf2zh/lib64/python3.12/site-packages/pymupdf/mupdf.py", line 53759, in pdf_write_document
    return _mupdf.pdf_write_document(doc, out, opts)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pymupdf.mupdf.FzErrorFormat: code=7: cannot parse object (1392 0 R)
```

## 测试文档
[doc.pdf](https://people.freebsd.org/~lstewart/articles/cpumemory.pdf)

**Comment by xpww** [comment]
你好，我也遇到了这个问题，而且是一开始就出错，你这里有办法解决吗

**Comment by zpofrp** [comment]
这个问题找到解决办法了吗？

**Comment by LifeCheckpoint** [comment]
我也遇到了类似问题，这里有个解决方案：

使用 Acrobat 打开 PDF，选择“优化 PDF” -> “印前检查”，找到如下选项并执行

![Image](https://github.com/user-attachments/assets/6496d7b0-d096-41a4-85e7-f5b67246c5a5)

似乎能够让 PDF 解析成功，但是不知道效果如何

**Comment by xpww** [comment]
我的问题在于pdf是加密的，似乎pdf2zh就难以识别。解密后，再去除水印就好了。pdf解密可以在吾爱破解论坛找到
