### ISSUE TITLE
urllib.error.URLError: <urlopen error [WinError 10061]

### ISSUE THREAD

**Issue by yuzixieshouhuajiaqi** [Byaidu/PDFMathTranslate#363]
已经成功运行了几天，翻译了几个PDF后，就出现了下面的错误代码，本人非计算机相关专业，检索了很久，看不懂怎么回事，麻烦大佬有空时，提示一下 解决的方向。 
PS C:\Users\hj> pdf2zh http://arxiv.org/paper.pdf
Downloading...
Traceback (most recent call last):
  File "D:\python\Lib\urllib\request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "D:\python\Lib\http\client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\python\Lib\http\client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\python\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\python\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
  File "D:\python\Lib\http\client.py", line 1035, in send
    self.connect()
  File "D:\python\Lib\http\client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\socket.py", line 865, in create_connection
    raise exceptions[0]
  File "D:\python\Lib\socket.py", line 850, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
  File "D:\python\Lib\site-packages\pdf2zh\pdf2zh.py", line 225, in main
    extract_text(**vars(parsed_args))
  File "D:\python\Lib\site-packages\pdf2zh\pdf2zh.py", line 73, in extract_text
    urllib.request.urlretrieve("http://huggingface.co/juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt",pth)
  File "D:\python\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\urllib\request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\urllib\request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "D:\python\Lib\urllib\request.py", line 1373, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\Lib\urllib\request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10061] 由于目标计算机积极拒绝，无法连接。>

**Comment by 361586** [comment]
网络问题,开全局代理或者控制台设置代理
