### ISSUE TITLE
Error reCAPTCHA fail这是什么原因？

### ISSUE THREAD

**Issue by 1024AD** [Byaidu/PDFMathTranslate#382]
### 问题一：使用提供的网页版总是出现这个问题，换了别的pdf也不行。
![293b682c12fc08db8ad1ca418899ed3](https://github.com/user-attachments/assets/f22a21b2-5c4d-486a-96b0-211feddd014c)
![9657edfead8d5b0e33e133849d35677](https://github.com/user-attachments/assets/c0956949-aae0-45d5-a7f4-2dd3dfa5ee26)

### 问题二：在linux上运行也出错。
```
alan@ubuntu:~/桌面/PDFMathTranslate$ pdf2zh Extremely-Low_Threshold_Voltage_FinFET_for_5G_mmWave_Applications.pdf
Traceback (most recent call last):
  File "/home/alan/.local/bin/pdf2zh", line 8, in <module>
    sys.exit(main())
  File "/home/alan/.local/lib/python3.8/site-packages/pdf2zh/pdf2zh.py", line 274, in main
    extract_text(**vars(parsed_args))
  File "/home/alan/.local/lib/python3.8/site-packages/pdf2zh/pdf2zh.py", line 74, in extract_text
    import pdf2zh.high_level
  File "/home/alan/.local/lib/python3.8/site-packages/pdf2zh/high_level.py", line 12, in <module>
    from pdf2zh.converter import (
  File "/home/alan/.local/lib/python3.8/site-packages/pdf2zh/converter.py", line 22, in <module>
    from pdf2zh.translator import (
  File "/home/alan/.local/lib/python3.8/site-packages/pdf2zh/translator.py", line 8, in <module>
    import ollama
  File "/home/alan/.local/lib/python3.8/site-packages/ollama/__init__.py", line 40, in <module>
    _client = Client()
  File "/home/alan/.local/lib/python3.8/site-packages/ollama/_client.py", line 115, in __init__
    super().__init__(httpx.Client, host, **kwargs)
  File "/home/alan/.local/lib/python3.8/site-packages/ollama/_client.py", line 95, in __init__
    self._client = client(
  File "/home/alan/.local/lib/python3.8/site-packages/httpx/_client.py", line 693, in __init__
    proxy_map = self._get_proxy_map(proxies or proxy, allow_env_proxies)
  File "/home/alan/.local/lib/python3.8/site-packages/httpx/_client.py", line 218, in _get_proxy_map
    return {
  File "/home/alan/.local/lib/python3.8/site-packages/httpx/_client.py", line 219, in <dictcomp>
    key: None if url is None else Proxy(url=url)
  File "/home/alan/.local/lib/python3.8/site-packages/httpx/_config.py", line 338, in __init__
    raise ValueError(f"Unknown scheme for proxy URL {url!r}")
ValueError: Unknown scheme for proxy URL URL('socks://127.0.0.1:7897/')
```
请各位帮我看下是什么问题。
## 测试文档
> [!IMPORTANT]
> 请提供用于复现测试的 PDF 文档
[Extremely-Low_Threshold_Voltage_FinFET_for_5G_mmWave_Applications.pdf](https://github.com/user-attachments/files/18278849/Extremely-Low_Threshold_Voltage_FinFET_for_5G_mmWave_Applications.pdf)

**Comment by Byaidu** [comment]
1. 大概是 reCAPTCHA 用完了，近期会修

2. 暂时不支持 socks 代理
