### ISSUE TITLE
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by ZhiYuan1688** [Byaidu/PDFMathTranslate#4]
模型通过脚本下载和手动下载都报这个错误
似乎是文件损坏或错误导致
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\python311\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
  File "D:\python311\Lib\site-packages\pdf2zh\pdf2zh.py", line 200, in main
    extract_text(**vars(parsed_args))
  File "D:\python311\Lib\site-packages\pdf2zh\pdf2zh.py", line 71, in extract_text
    model = lp.EfficientDetLayoutModel("lp://efficientdet/MFD/tf_efficientdet_d0",pth)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\layoutparser\models\effdet\layoutmodel.py", line 138, in __init__
    self._initialize_model(config_path, model_path, label_map, extra_config)
  File "D:\python311\Lib\site-packages\layoutparser\models\effdet\layoutmodel.py", line 166, in _initialize_model
    self.model = create_model(
                 ^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\effdet\factory.py", line 12, in create_model
    return create_model_from_config(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\effdet\factory.py", line 48, in create_model_from_config
    load_checkpoint(model, checkpoint_path, use_ema=checkpoint_ema)
  File "D:\python311\Lib\site-packages\timm\models\_helpers.py", line 96, in load_checkpoint
    state_dict = load_state_dict(checkpoint_path, use_ema, device=device, weights_only=weights_only)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\timm\models\_helpers.py", line 56, in load_state_dict
    checkpoint = torch.load(checkpoint_path, map_location=device, weights_only=weights_only)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\torch\serialization.py", line 1072, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python311\Lib\site-packages\torch\serialization.py", line 480, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by ZhiYuan1688** [comment]
windows 11

**Comment by Byaidu** [comment]
我这里 Windows 11 运行是没问题的，建议检查一下模型文件哈希

```bash
$ sha1sum ./mfd-tf_efficientdet_d0.pth.tar
995bd4aff51d3b5de772c9e02f59e2735fb80cdb  ./mfd-tf_efficientdet_d0.pth.tar
```

**Comment by ZhiYuan1688** [comment]
> 我这里 Windows 11 运行是没问题的，建议检查一下模型文件哈希
> 
> ```shell
> $ sha1sum ./mfd-tf_efficientdet_d0.pth.tar
> 995bd4aff51d3b5de772c9e02f59e2735fb80cdb  ./mfd-tf_efficientdet_d0.pth.tar
> ```

F153E0CFE3C987981AB2D02CE32C8A5FA0B4092BC97ABCF95C887E2E05BD4003这是我的hash 文件名tf_efficientdet_d0_34-f153e0cf.pth

**Comment by Byaidu** [comment]
你这个 pth 的哈希是对的，但是不知道 pth.tar 的对不对

**Comment by ZhiYuan1688** [comment]
> 你这个 pth 的哈希是对的，但是不知道 pth.tar 的对不对

下载下来 只有.pth 没有.tar的

**Comment by Byaidu** [comment]
这里下载 pth.tar

https://www.dropbox.com/s/dkr22iux7thlhel/mfd-tf_efficientdet_d0.pth.tar?dl=1

**Comment by ZhiYuan1688** [comment]
> 这里下载 pth.tar
> 
> https://www.dropbox.com/s/dkr22iux7thlhel/mfd-tf_efficientdet_d0.pth.tar?dl=1

存放到这里吗 //efficientdet/MFD/

**Comment by Byaidu** [comment]
存放到 `tempfile.gettempdir()` 对应的目录下

一般来说是 `C:\Users\xxx\AppData\Local\Temp`

**Comment by ZhiYuan1688** [comment]
感谢 已解决

**Comment by QHQ-QHQ** [comment]
> windows 11

请问你将下载的mfd-tf_efficientdet_d0.pth.tar文件放在哪个文件夹里了呀？我在C:\Users\xxx\AppData\Local\Temp没有找到对应的文件夹，直接放在C:\Users\xxx\AppData\Local\Temp文件夹中还是会报错

**Comment by duskdusts** [comment]
#

> > windows 11
> 
> 请问你将下载的mfd-tf_efficientdet_d0.pth.tar文件放在哪个文件夹里了呀？我在C:\Users\xxx\AppData\Local\Temp没有找到对应的文件夹，直接放在C:\Users\xxx\AppData\Local\Temp文件夹中还是会报错

俺也一样，报错好像和哥们你的差不多，不知道放哪
