### ISSUE TITLE
pymupdf.mupdf.FzErrorFormat: code=7: cannot find object in xref (8683 0 R)

### ISSUE THREAD

**Issue by yshi100** [Byaidu/PDFMathTranslate#40]
ckpt = torch.load(file, map_location="cpu")
Traceback (most recent call last):
  File "/home/yshi/.pyenv/versions/3.12.0/bin/pdf2zh", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 229, in main
    extract_text(**vars(parsed_args))
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pdf2zh/pdf2zh.py", line 90, in extract_text
    font_res=doc_en.xref_get_key(xref,f'{label}Font')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pymupdf/__init__.py", line 5987, in xref_get_key
    obj = mupdf.pdf_load_object(pdf, xref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yshi/.pyenv/versions/3.12.0/lib/python3.12/site-packages/pymupdf/mupdf.py", line 50782, in pdf_load_object
    return _mupdf.pdf_load_object(doc, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[The Software Developers Guide to Linux A practical, no-nonsense guide to using the Linux command line and utilities as a... (David Cohen, Christian Sturm) (Z-Library).pdf](https://github.com/user-attachments/files/17711308/The.Software.Developers.Guide.to.Linux.A.practical.no-nonsense.guide.to.using.the.Linux.command.line.and.utilities.as.a.David.Cohen.Christian.Sturm.Z-Library.pdf)

**Comment by Byaidu** [comment]
已修复
