### ISSUE TITLE
新手请求帮助

### ISSUE THREAD

**Issue by QHQ-QHQ** [Byaidu/PDFMathTranslate#52]
你好，我下载python是Python 3.11.9，按照文件要求是的使用pip安装pip install pdf2zh完成，之后我在test文件中放入一个名称为21.pdf的文件，在命令行中执行，PS C:\Users\QHQ\Desktop\test> pdf2zh 21.pdf，出现以下问题，请问能帮忙看一下这是为什么嘛？

PS C:\Users\QHQ\Desktop\test> pdf2zh 21.pdf
C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\doclayout_yolo\nn\tasks.py:733: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckpt = torch.load(file, map_location="cpu")
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdf2zh\pdf2zh.py", line 229, in main
    extract_text(**vars(parsed_args))
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdf2zh\pdf2zh.py", line 74, in extract_text
    model = doclayout_yolo.YOLOv10(pth)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\doclayout_yolo\models\yolov10\model.py", line 10, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\doclayout_yolo\engine\model.py", line 144, in __init__
    self._load(model, task=task)
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\doclayout_yolo\engine\model.py", line 233, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\doclayout_yolo\nn\tasks.py", line 807, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\doclayout_yolo\nn\tasks.py", line 733, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 1326, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\QHQ\AppData\Local\Programs\Python\Python311\Lib\site-packages\torch\serialization.py", line 671, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by Byaidu** [comment]
参考 https://github.com/Byaidu/PDFMathTranslate/issues/4

**Comment by duskdusts** [comment]
我是下载了pdf2zh.py里面的http://huggingface.co/juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt的模型，复制到C:\Users\username\AppData\Local\Temp里面解决的

**Comment by QHQ-QHQ** [comment]
> 我是下载了pdf2zh.py里面的[http://huggingface.co/juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt的模型，复制到C:\Users\username\AppData\Local\Temp里面解决的](http://huggingface.co/juliozhao/DocLayout-YOLO-DocStructBench/resolve/main/doclayout_yolo_docstructbench_imgsz1024.pt%E7%9A%84%E6%A8%A1%E5%9E%8B%EF%BC%8C%E5%A4%8D%E5%88%B6%E5%88%B0C:%5CUsers%5Cusername%5CAppData%5CLocal%5CTemp%E9%87%8C%E9%9D%A2%E8%A7%A3%E5%86%B3%E7%9A%84)

谢谢你，按照您的方法，已经完美解决，非常感谢
