### ISSUE TITLE
ValueError: check_hostname requires server_hostname

### ISSUE THREAD

**Issue by yi00liang** [Byaidu/PDFMathTranslate#70]
return ssl_context.wrap_socket(sock)
  File "D:\ProgramData\Anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\ProgramData\Anaconda3\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by Byaidu** [comment]
麻烦贴上完整的日志

**Comment by yi00liang** [comment]
> 麻烦贴上完整的日志
C:\Users\Administrator>pdf2zh --version
pdf2zh v1.7.5
C:\Users\Administrator>pdf2zh ss.pdf
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\ProgramData\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\ProgramData\Anaconda3\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\ProgramData\Anaconda3\lib\site-packages\pdf2zh\pdf2zh.py", line 262, in main
    extract_text(**vars(parsed_args))
  File "D:\ProgramData\Anaconda3\lib\site-packages\pdf2zh\pdf2zh.py", line 87, in extract_text
    pth = hf_hub_download(repo_id="juliozhao/DocLayout-YOLO-DocStructBench", filename="doclayout_yolo_docstructbench_imgsz1024.pt")
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 862, in hf_hub_download
    return _hf_hub_download_to_cache_dir(
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 925, in _hf_hub_download_to_cache_dir
    (url_to_download, etag, commit_hash, expected_size, head_call_error) = _get_metadata_or_catch_error(
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 1376, in _get_metadata_or_catch_error
    metadata = get_hf_file_metadata(
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 1296, in get_hf_file_metadata
    r = _request_wrapper(
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 277, in _request_wrapper
    response = _request_wrapper(
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\file_download.py", line 300, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\huggingface_hub\utils\_http.py", line 93, in send
    return super().send(request, *args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 696, in urlopen
    self._prepare_proxy(conn)
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connectionpool.py", line 964, in _prepare_proxy
    conn.connect()
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 359, in connect
    conn = self._connect_tls_proxy(hostname, conn)
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\connection.py", line 500, in _connect_tls_proxy
    return ssl_wrap_socket(
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls)
  File "D:\ProgramData\Anaconda3\lib\site-packages\urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock)
  File "D:\ProgramData\Anaconda3\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "D:\ProgramData\Anaconda3\lib\ssl.py", line 997, in _create
    raise ValueError("check_hostname requires server_hostname")
ValueError: check_hostname requires server_hostname

**Comment by yi00liang** [comment]
@Byaidu #55 提供的解决办法看不懂如何操作，我的理解进行了下边的操作
C:\Users\Administrator>pip install --upgrade certifi
WARNING: Ignoring invalid distribution -ip (d:\programdata\anaconda3\lib\site-packages)
Requirement already satisfied: certifi in d:\programdata\anaconda3\lib\site-packages (2024.8.30)
WARNING: Error parsing dependencies of pyodbc: Invalid version: '4.0.0-unsupported'
WARNING: Error parsing dependencies of pyzmq: Invalid version: 'cpython'
WARNING: Ignoring invalid distribution -ip (d:\programdata\anaconda3\lib\site-packages)
但是依然未解决问题

**Comment by Byaidu** [comment]
搞不定网络问题可以考虑直接用 docker 版本

**Comment by yi00liang** [comment]
@Byaidu 哈哈哈对

**Comment by reycn** [comment]
See [wiki FAQ](https://github.com/Byaidu/PDFMathTranslate/wiki/Frequently-Asked-Questions#ssl-issues-and-other-network-issues)

**Comment by yi00liang** [comment]
@reycn 拉取出现问题
C:\Users\Administrator>docker login
Authenticating with existing credentials...
Login Succeeded
C:\Users\Administrator>docker pull byaidu/pdf2zh
Using default tag: latest
What's next:
    View a summary of image vulnerabilities and recommendations → docker scout quickview byaidu/pdf2zh
Error response from daemon: failed to resolve reference "docker.io/byaidu/pdf2zh:latest": pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials

**Comment by reycn** [comment]
> @reycn 拉取出现问题 C:\Users\Administrator>docker login Authenticating with existing credentials... Login Succeeded C:\Users\Administrator>docker pull byaidu/pdf2zh Using default tag: latest What's next: View a summary of image vulnerabilities and recommendations → docker scout quickview byaidu/pdf2zh Error response from daemon: failed to resolve reference "docker.io/byaidu/pdf2zh:latest": pull access denied, repository does not exist or may require authorization: authorization failed: no basic auth credentials

Confirmed and new issue created. Please use `docker pull byaidu/pdf2zh:1.7.6` for now.

**Comment by yi00liang** [comment]
@reycn 使用docker desktop进行拉取和运行的话，没有端口映射，打不开http://localhost:7860/，只能使用命令行docker run -d -p 7860:7860 your_image_name重新进行运行才行。
