### ISSUE TITLE
input-en.pdf 文件访问无权限

### ISSUE THREAD

**Issue by Zxis233** [Byaidu/PDFMathTranslate#84]
## 问题描述

使用OpenAI翻译，身份验证正常，使用`git-4o-mini`模型翻译后，进度条正常走完，但报错：
```
Executing command: cd "R:\Temp\tmpu5gmxg3g" && pdf2zh "R:\Temp\tmpu5gmxg3g\input.pdf" -lo zh -s openai:gpt-4o-mini  -p 1
Files in temp directory: ['input.pdf']
Command output: C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\doclayout_yolo\nn\tasks.py:733: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
Command output: ckpt = torch.load(file, map_location="cpu")
Command output: Traceback (most recent call last):
Command output: File "<frozen runpy>", line 198, in _run_module_as_main
Command output: File "<frozen runpy>", line 88, in _run_code
Command output: File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Scripts\pdf2zh.exe\__main__.py", line 7, in <module>
Command output: File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdf2zh\pdf2zh.py", line 262, in main
Command output: extract_text(**vars(parsed_args))
Command output: File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pdf2zh\pdf2zh.py", line 113, in extract_text
Command output: doc_en.save(f'{filename}-en.pdf')
Command output: File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymupdf\__init__.py", line 5659, in save
Command output: mupdf.pdf_save_document(pdf, filename, opts)
Command output: File "C:\Users\Admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pymupdf\mupdf.py", line 51731, in pdf_save_document
Command output: return _mupdf.pdf_save_document(doc, filename, opts)
Command output: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Command output: pymupdf.mupdf.FzErrorSystem: code=2: cannot remove file 'input-en.pdf': Permission denied
Command completed with return code: 1
Files after translation: ['input.pdf']
Translation failed: No output files found
```

## 测试文档
[electronics-11-03244-v3.pdf](https://github.com/user-attachments/files/17839680/electronics-11-03244-v3.pdf)

**Comment by Byaidu** [comment]
可以看下是不是用阅读器打开文件导致文件占用了

**Comment by reycn** [comment]
The bug has been fixed [fix (main): permission error](https://github.com/Byaidu/PDFMathTranslate/commit/8a66da7842c660d5e666193267ec3c563a8e3ced)
